# GitHub Sponsors
github: [carlymariec]

# Optional platforms (uncomment and fill in if you use them)
# patreon: your-patreon
# open_collective: your-open-collective
# ko_fi: your-ko-fi
# buy_me_a_coffee: your-buymeacoffee
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: your-liberapay
# issuehunt: your-issuehunt
# otechie: your-otechie
# lfx_crowdfunding: project-name
# polar: your-polar
# custom: ['https://your-donation-link.example']
